# Adapted from https://github.com/maxpou/docker-symfony/blob/master/docker-compose.yml

version: "2"

services:
    db:
        image: mysql:5.7.22
        volumes:
            - "./.data/db:/var/lib/mysql"
        ports:
            - 4001:3306
        environment:
            MYSQL_ROOT_PASSWORD: metrics 
            MYSQL_DATABASE: metrics
            MYSQL_USER: metrics
            MYSQL_PASSWORD: metrics

    app:
        build:
            context: docker/app
            args:
                TIMEZONE: ${TIMEZONE}
        ports:
            - 4002:9000
        volumes:
            - .:/var/www/app

    web:
        build: docker/nginx
        ports:
            - 4000:80
        volumes_from:
            - app
        volumes:
            - ./logs/nginx/:/var/log/nginx

    stats:
        image: graphiteapp/docker-graphite-statsd:latest
        ports:
            - 4003:80
            - 4004:8126
